# Generated by Django 6.1 on 2026-08-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.JSONField()),
                ('turn', models.CharField(default='white', max_length=5)),
                ('status', models.CharField(default='ongoing', max_length=20)),
                ('moves_log', models.CharField(max_length=50)),
            ],
        ),
    ]
