# Generated by Django 6.1 on 2026-08-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='moves_log',
            field=models.JSONField(),
        ),
    ]
