# Generated by Django 6.1 on 2026-09-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_chessgame_moves_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='vs_ai',
            field=models.BooleanField(default=False),
        ),
    ]
