# Generated by Django 6.1 on 2026-09-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_chessgame_vs_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='castling_flags',
            field=models.JSONField(default={'black': {'kingside': True, 'queenside': True}, 'white': {'kingside': True, 'queenside': True}}),
            preserve_default=False,
        ),
    ]
