# Generated by Django 6.1 on 2026-09-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_chessgame_castling_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='board_snapshots',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
