# Generated by Django 6.1 on 2026-09-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_chessgame_board_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='board_snapshots',
            field=models.JSONField(default=list),
        ),
    ]
