# Generated by Django 6.1 on 2026-09-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_chessgame_board_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='difficulty',
            field=models.CharField(default='medium', max_length=10),
        ),
    ]
